[ccipv17]
  # LINK token contract address (static for Anvil and testnets)
  link_contract_address = "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
  # Chainlink node funding in ETH (1**18 wei)
  cl_nodes_funding_eth = 50
  # Chainlink node funding in LINK (1**18 wei)
  cl_nodes_funding_link = 50
  # amount of time we'll wait for the first feed answer, if there is no answer environment is not working
  verification_timeout = 400
  # contracts configuration timeout (seconds)
  contracts_configuration_timeout = 60
  # target blockchain finality depth
  chain_finality_depth = 5
  # whether to verify product deployment or not
  verify = true

  [ccipv17.gas_settings]
  # EIP1159 fee cap multiplier (default, for all transactions)
  fee_cap_multiplier = 2
  # EIP1159 fee cap multiplier (default, for all transactions)
  tip_cap_multiplier = 2

  [ccipv17.ea_fake]
    # low response value of fake External Adapter
    # values are chosen randomly, either low or high
    low_value = 3
    # high response value of a fake External Adapter
    high_value = 30000

  [ccipv17.jobs]
    # OCRv2 config refresh interval, query the chain and get the latest config
    config_poll_interval_sec = 5
    # maximum job task duration in Go duration in seconds
    max_task_duration_sec = 60

[[blockchains]]
  chain_id = "1337"
  docker_cmd_params = ["-b", "1"]
  image = "f4hrenh9it/foundry:latest"
  port = "8545"
  type = "anvil"

[[blockchains]]
  chain_id = "2337"
  docker_cmd_params = ["-b", "1"]
  image = "f4hrenh9it/foundry:latest"
  port = "8555"
  type = "anvil"

[storage_provider]
  host = "minio"
  port = 9000
  console_port = 9001
  # these are default local MinIO keys, they are also setup in flake.nix
  access_key = "mYrAnD0mAcc3ssK3y2024"
  secret_key = "s3cR3tK3yL0ngEn0ughF0rMinI0Testing2024!"
  bucket = "test"
  region = "us-west-2"

[jd]
  csa_encryption_key = "1a3f7e9d2c5b8a0f4e6d9c2b7a1e5f3d8c0b9a8d7f6e5c4b3a2d1e0f9a8b7c1a"
  image = "804282218731.dkr.ecr.us-west-2.amazonaws.com/job-distributor:0.12.7"

[fake_server]
  # go to fakes dir, build your mocks and put your image here
  image = "f4hrenh9it/df-fakes:latest"
  port = 9111

# this is an example config of a new ccip service that can be integrated, see "services/indexer.go" and read README in that dir
# since the prodct is in early stages we run dev images by default, with hot-reload
[indexer]
  image = "indexer:dev"
  port = 8100
  # path is relative from "devenv" dir
  source_code_path = "ccipv1_7/indexer"
  [indexer.db]
    image = "postgres:16-alpine"

[[nodesets]]
  name = "don"
  nodes = 4
  override_mode = "each"

  [nodesets.db]
    image = "postgres:15.0"

  [[nodesets.node_specs]]

    [nodesets.node_specs.node]
      image = "public.ecr.aws/chainlink/chainlink:2.26.0"

  [[nodesets.node_specs]]

    [nodesets.node_specs.node]
      image = "public.ecr.aws/chainlink/chainlink:2.26.0"

  [[nodesets.node_specs]]

    [nodesets.node_specs.node]
      image = "public.ecr.aws/chainlink/chainlink:2.26.0"

  [[nodesets.node_specs]]

    [nodesets.node_specs.node]
      image = "public.ecr.aws/chainlink/chainlink:2.26.0"
