[[blockchains]]
  container_name = "blockchain-src"
  chain_id = "1337"
  port = "8545"
  type = "geth"

[[blockchains]]
  container_name = "blockchain-dst"
  chain_id = "2337"
  port = "8555"
  type = "geth"

[[blockchains]]
  container_name = "solana-chain"
  chain_id = "EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG"
  port = "8565"
  type = "solana"