cl_nodes_funding_eth = 50
cl_nodes_funding_link = 50

[cldf]

[[blockchains]]
  container_name = "blockchain-src"
  chain_id = "1337"
  docker_cmd_params = ["-b", "1", "--mixed-mining", "--slots-in-an-epoch", "1"]
  image = "ghcr.io/foundry-rs/foundry:latest"
  port = "8545"
  type = "anvil"

[[blockchains]]
  container_name = "blockchain-dst"
  chain_id = "2337"
  docker_cmd_params = ["-b", "1", "--mixed-mining", "--slots-in-an-epoch", "1"]
  image = "ghcr.io/foundry-rs/foundry:latest"
  port = "8555"
  type = "anvil"

[[blockchains]]
  container_name = "solana-chain"
  chain_id = "22222222222222222222222222222222222222222222"
  port = "8565"
  type = "solana"
  public_key = "HxwS3jBBSoK6EUJ7L4FGXo8aAsMVEGGWQ2ZL7HT1ao1K"
  contracts_dir = "/tmp/solana-contracts"

[[blockchains]]
  container_name = "ton-chain"
  chain_id = "-217"
  type = "ton"
  image = "ghcr.io/neodix42/mylocalton-docker:v3.97"
  port = "8575"
  custom_env = {VERSION_CAPABILITIES = "12", NEXT_BLOCK_GENERATION_DELAY = "0.5"}

[jd]
  csa_encryption_key = "1a3f7e9d2c5b8a0f4e6d9c2b7a1e5f3d8c0b9a8d7f6e5c4b3a2d1e0f9a8b7c1a"
  image = "job-distributor:local"

[[nodesets]]
  name = "don"
  nodes = 6
  override_mode = "each"

  [nodesets.db]
    image = "postgres:15.0"

  [[nodesets.node_specs]]

    [nodesets.node_specs.node]
      image = "chainlink:develop"

  [[nodesets.node_specs]]

    [nodesets.node_specs.node]
      image = "chainlink:develop"

  [[nodesets.node_specs]]

    [nodesets.node_specs.node]
      image = "chainlink:develop"

  [[nodesets.node_specs]]

    [nodesets.node_specs.node]
      image = "chainlink:develop"

  [[nodesets.node_specs]]

    [nodesets.node_specs.node]
      image = "chainlink:develop"
  
  [[nodesets.node_specs]]

    [nodesets.node_specs.node]
      image = "chainlink:develop"
