[[blockchains]]
  container_name = "blockchain-src"
  chain_id = "1337"
  docker_cmd_params = ["-b", "1", "--mixed-mining", "--slots-in-an-epoch", "1"]
  image = "ghcr.io/foundry-rs/foundry:latest"
  port = "8545"
  type = "anvil"

[[blockchains]]
  container_name = "solana-chain"
  chain_id = "22222222222222222222222222222222222222222222"
  port = "8565"
  type = "solana"
  public_key = "HxwS3jBBSoK6EUJ7L4FGXo8aAsMVEGGWQ2ZL7HT1ao1K"
  contracts_dir = "/tmp/solana-contracts"
