[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "id.json"
# wallet = "~/.config/solana/id.json"

# [programs.mainnet]
# TODO: add pubkeys

# [programs.testnet]
# TODO: add pubkeys

# [programs.devnet]
# TODO: add pubkeys

[programs.localnet]
access_controller = "9xi644bRR8birboDGdTiwBq3C7VEeR7VuamRYYXCubUW"
ccip_receiver = "CtEVnHsQzhTNWav8skikiV2oF6Xx7r7uGGa8eCDQtTjH"
ccip_invalid_receiver = "9Vjda3WU2gsJgE4VdU6QuDw8rfHLyigfFyWs3XDPNUn8"
ccip_router = "C8WSPj3yyus1YN3yNB6YA5zStYtbjQWtpmKadmvyUXq8"
token_pool = "GRvFSLwR7szpjgNEZbGe4HtxfJYXqySXuuRUAJDpu4WH"
external_program_cpi_stub  = "4HeqEoSyfYpeC2goFLj9eHgkxV33mR5G7JYAbRsN14uQ"
mcm = "6UmMZr5MEqiKWD5jqTJd1WCR5kT8oZuFYBLJFi1o6GQX"
timelock = "LoCoNsJFuhTkSQjfdDfn3yuwqhSYoPujmviRHVCzsqn"
fee_quoter = "FeeVB9Q77QvyaENRL1i77BjW6cTkaWwNLjNbZg9JHqpw"
