name: Smoke tests (devenv)

on:
  workflow_dispatch:
    inputs:
      ton_ref:
        description: 'Git ref (branch) of the TON relayer'
        required: false
        type: string
      contract_version:
        description: 'Version of CCIP contracts to use'
        required: false
        type: string
      chainlink_version:
        description: 'Chainlink version to use (e.g., develop, gh ref, etc.)'
        required: false
        type: string
      custom_config:
        description: "Extra config file(s), e.g. ton.toml,sui.toml"
        required: false
        type: string
  workflow_call:
    inputs:
      ton_ref:
        description: 'Git ref (branch) of the TON relayer'
        required: false
        type: string
      contract_version:
        description: 'Version of CCIP contracts to use'
        required: false
        type: string
      chainlink_version:
        description: 'Chainlink version to use (e.g., develop, gh ref, etc.)'
        required: false
        type: string
      custom_config:
        description: "Extra config file(s), e.g. ton.toml,sui.toml"
        required: false
        type: string
  pull_request:
  push:
    branches:
      - 'main'

defaults:
  run:
    working-directory: devenv

env:
  PARALLEL_E2E_TESTS: 'true'
  DEPLOY_CONTRACT_VERSION: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.contract_version || '' }}

jobs:
  smoke:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu24.04-16cores-64GB
    strategy:
      matrix:
        test:
        - name: TestE2ESmoke
          config: "env.toml"                     # only the base config
        - name: TestE2ESmoke
          config: >-
            ${{ 
                github.event_name == 'workflow_dispatch' &&
                ( inputs.custom_config != '' && inputs.custom_config || 'env.toml,solana.toml' )
                || 'env.toml,solana.toml'
            }}
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - name: Checkout Chainlink TON
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ton_ref != '' }}
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: smartcontractkit/chainlink-ton
          ref: ${{ github.event.inputs.ton_ref }}
          path: chainlink-ton
      - name: Build CL Image For Ref
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.chainlink_version != '' }}
        uses: ./.github/actions/build-cl
        with:
          ton_ref: ${{ github.event.inputs.ton_ref || '' }}
          chainlink_version: ${{ github.event.inputs.chainlink_version }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Install Just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3
        with:
          just-version: '1.40.0'
      - name: Authenticate to AWS ECR
        uses: ./.github/actions/aws-ecr-auth
        with:
          role-to-assume: ${{ secrets.CCIP_IAM_ROLE }}
          aws-region: us-east-1
          registry-type: public
      - name: Authenticate to AWS ECR (JD)
        uses: ./.github/actions/aws-ecr-auth
        with:
          role-to-assume: ${{ secrets.CCV_IAM_ROLE }}
          aws-region: us-west-2
          registry-type: private
          registries: ${{ secrets.JD_REGISTRY }}
      - name: Set up Go
        uses: actions/setup-go@v6 # v6
        with:
          cache: true
          go-version-file: devenv/go.mod
          cache-dependency-path: |
            devenv/go.sum
      - name: Download Go dependencies
        run: |
          export GOPRIVATE=github.com/smartcontractkit/*
          if [ -n "${{ inputs.ton_ref }}" ]; then
            go get github.com/smartcontractkit/chainlink-ton/devenv-impl@${{ inputs.ton_ref }}
            go get github.com/smartcontractkit/chainlink-ton/deployment@${{ inputs.ton_ref }}
            go get github.com/smartcontractkit/chainlink-ton@${{ inputs.ton_ref }}
          fi
          go mod download
      - name: Run CCIP environment with config
        env:
          JD_IMAGE: ${{ secrets.JD_IMAGE }}
        run: |
          cd cmd/ccip && go install . && cd -
          ccip u ${{ matrix.test.config }}
          sleep 120 # wait for nodes to be ready, need a better way here
      - name: Run smoke test
        working-directory: devenv/tests/e2e
        run: |
          go test -v -run ${{ matrix.test.name }} -timeout 20m
